### PR TITLE
CTS-EpiDoc-ized Hesiod Theogony to annotsrc for Vortex

### PR DESCRIPTION
**Pull request by srdee**
https://github.com/PerseusDL/perseids_docs/issues/239

### CODE REVIEW

**Comment by srdee** [comment]
@annakrohn new EpiDoc versions for the Catalogue (tlg0020.tlg001.perseus-grc2 and tlg0020.tlg001.perseus-eng2)

**Comment by balmas** [comment]
@srdee -- can you double check whether you have the master version of annotsrc.xml as your base? I think the # of changes looks too big -- some are spacing differences but it looks like we might have lost some of the texts from it in this commit. Thanks!

**Comment by srdee** [comment]
@balmas I just checked in a diff tool, and nothing seems to have been lost! I just updated my repo before I made the changes--I clicked the 'format' tool in Oxygen and it seems to have re-spaced things in sometimes odd ways, but the data looks to be all the same.

**Comment by srdee** [comment]
@balmas is there a particular text that makes you think texts were lost, or just the number?

**Comment by balmas** [comment]
if you checked in oXygen then I think we are probably fine. It looked like Athenaeus was missing but I was looking very quickly at the diff on the command line.

**Comment by balmas** [comment]
ah, I think maybe I had and old version of your branch locally.

**Pull request merged**
